### ISSUE TITLE
Cloned, npm install and ng serve: Promise rejection error!

### ISSUE THREAD

**Issue by oberoivarun** [ngrx/example-app#105]
Simply followed instructions: `git clone, npm install and then ng serve`. The following shows on localhost:4200:

```
Unhandled Promise rejection: Cannot read property '0' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property '0' of undefined
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6514:115
    at Array.reduce (native)
    at resolveNgModuleDecoratorConfig (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6513:30)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6626:42
    at Array.forEach (native)
    at _parseModule (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6621:22)
    at Object.exports.parseModules (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6521:15)
    at parseInitialModules (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9403:89)
    at bind (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9443:6)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9461:71
    at Array.forEach (native)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9461:38
    at checkDebug (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9450:10)
    at resubscribe (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9455:6)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9464:94 TypeError: Cannot read property '0' of undefined
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6514:115
    at Array.reduce (native)
    at resolveNgModuleDecoratorConfig (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6513:30)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6626:42
    at Array.forEach (native)
    at _parseModule (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6621:22)
    at Object.exports.parseModules (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:6521:15)
    at parseInitialModules (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9403:89)
    at bind (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9443:6)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9461:71
    at Array.forEach (native)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9461:38
    at checkDebug (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9450:10)
    at resubscribe (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9455:6)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:9464:94
consoleError @ zone.js:420
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
ZoneTask.invoke @ zone.js:349
zone.js:422 
```

**Comment by brandonroberts** [comment]
Will you add more context about your environment.  Node/npm versions, operating system, etc...

**Comment by oberoivarun** [comment]
Windows 10 
Node 6.9.2
npm 3.10.9
global angular-cli : beta.26
Browser: Chrome (Latest)

Anything else you need?

**Comment by krjordan** [comment]
I'm unable to reproduce on OSX. Are you using the chrome Redux DevTools extension?

**Comment by oberoivarun** [comment]
Yes i am using the extension. But for some reason even i am not being able to reproduce the error anymore.

Yesterday i cloned the repo three times over and the error showed. Just a few minutes ago i did a 'ng new app' for another project and then saw your comment. Tried to serve the example-app and see the state tree in the redux extension, there were no errors anymore!

Sorry!

**Comment by krjordan** [comment]
Odd. If the error pops up again, let us know!

**Comment by goldenbearkin** [comment]
@brandonroberts  @krjordan 

I came across the same problem by using the angular-cli beta.30. I guess the problem is related to zone.js and ngrx-store-freeze library, so it should only happen in dev mode. Downgrading to zone.js 0.7.2, the problem is gone. After some investigation, seems like the zone.js has an ZoneAwareError Type which would wrap the exception you throw, but the ngrx-store-freeze has frozen your state object before the ZoneAwareError wrap around and therefore leading to TypeError mentioned above.

Reference: 
(look up for 'ZoneAwareError')
https://github.com/angular/zone.js/blob/master/CHANGELOG.md 

(look up for 'strict mode such attempts will throw TypeErrors')
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze
