### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by snellcode** [ngrx/example-app#135]
Can anyone help with this error when running `ng serve`? Error says:

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (./node_modules/@angular/cli/tasks/serve.js:22:63)
    at check_port_1.checkPort.then.port (./node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by snellcode** [comment]
nevermind, was missing the dotfiles, my mistake
