### ISSUE TITLE
ng e2e does not work right after clone example-app

### ISSUE THREAD

**Issue by sharikovvladislav** [ngrx/example-app#157]
Hi!

Steps:
1. `git clone git@github.com:ngrx/example-app.git`
2. `cd example-app`
3. `ng e2e`
4. Result is in the log (below):

Log:

```
sharikovvlad:angular2-try svlad$ git clone https://github.com/ngrx/example-app.git ngrx-example-app
Cloning into 'ngrx-example-app'...
remote: Counting objects: 872, done.
remote: Total 872 (delta 0), reused 0 (delta 0), pack-reused 871
Receiving objects: 100% (872/872), 4.86 MiB | 896.00 KiB/s, done.
Resolving deltas: 100% (477/477), done.
sharikovvlad:angular2-try svlad$ ccdcd ngrx-example-app
-bash: ccdcd: command not found
sharikovvlad:angular2-try svlad$ cd ngrx-example-app/
sharikovvlad:ngrx-example-app svlad$ yarn
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 26.27s.
sharikovvlad:ngrx-example-app svlad$ cd ..
sharikovvlad:angular2-try svlad$ git clone git@github.com:ngrx/example-app.git
Cloning into 'example-app'...
remote: Counting objects: 872, done.
remote: Total 872 (delta 0), reused 0 (delta 0), pack-reused 871
Receiving objects: 100% (872/872), 4.86 MiB | 1.27 MiB/s, done.
Resolving deltas: 100% (477/477), done.
sharikovvlad:angular2-try svlad$ cd example-app/
sharikovvlad:example-app svlad$ yarn
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 21.39s.
sharikovvlad:example-app svlad$ ng e2e
Your global Angular CLI version (1.0.6) is greater than your local
version (1.0.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is running on http://localhost:49152 **
(node:85646) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Hash: be9a11253a9465d875fc
Time: 13042ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 305 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 77.6 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 32.3 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.01 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
[02:29:15] I/file_manager - creating folder /Users/svlad/sandbox/angular2-try/example-app/node_modules/webdriver-manager/selenium
[02:29:16] I/downloader - curl -o /Users/svlad/sandbox/angular2-try/example-app/node_modules/webdriver-manager/selenium/chromedriver_2.30.zip https://chromedriver.storage.googleapis.com/2.30/chromedriver_mac64.zip
[02:29:18] I/update - chromedriver: unzipping chromedriver_2.30.zip
[02:29:18] I/update - chromedriver: setting permissions to 0755 for /Users/svlad/sandbox/angular2-try/example-app/node_modules/webdriver-manager/selenium/chromedriver_2.30
TypeError: Cannot find a tsconfig.json file at the specified directory: e2e
    at resolveSync (/Users/svlad/sandbox/angular2-try/example-app/node_modules/tsconfig/src/tsconfig.ts:71:11)
    at Object.loadSync (/Users/svlad/sandbox/angular2-try/example-app/node_modules/tsconfig/src/tsconfig.ts:142:16)
    at readConfig (/Users/svlad/sandbox/angular2-try/example-app/node_modules/ts-node/src/index.ts:417:18)
    at load (/Users/svlad/sandbox/angular2-try/example-app/node_modules/ts-node/src/index.ts:185:20)
    at service (/Users/svlad/sandbox/angular2-try/example-app/node_modules/ts-node/src/index.ts:363:32)
    at Object.register (/Users/svlad/sandbox/angular2-try/example-app/node_modules/ts-node/src/index.ts:372:5)
    at beforeLaunch (/Users/svlad/sandbox/angular2-try/example-app/protractor.conf.js:24:24)
    at q_1.Promise (/Users/svlad/sandbox/angular2-try/example-app/node_modules/protractor/lib/util.ts:48:39)
    at Function.promise (/Users/svlad/sandbox/angular2-try/example-app/node_modules/q/q.js:682:9)
    at Object.runFilenameOrFn_ (/Users/svlad/sandbox/angular2-try/example-app/node_modules/protractor/lib/util.ts:39:10)
    at Object.initFn [as init] (/Users/svlad/sandbox/angular2-try/example-app/node_modules/protractor/lib/launcher.ts:111:10)
    at promise.then (/Users/svlad/sandbox/angular2-try/example-app/node_modules/@angular/cli/tasks/e2e.js:62:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
sharikovvlad:example-app svlad$
```

It is because we have `tsconfig.e2e.ts`, but not `tsconfig.ts`.

If I fix it, right after it, I can run e2e tests, but they fail. They expect that there will be `app works` message on the main page.

**Comment by sharikovvladislav** [comment]
Can I try to make PR for this?

**Comment by krjordan** [comment]
Sure! However, the `example-app` is currently in the process of being integrated into the [ngrx/platform repo](https://github.com/ngrx/platform). Once [this PR](https://github.com/ngrx/platform/pull/12) gets merged in, you can submit your PR there.

**Comment by sharikovvladislav** [comment]
@krjordan any information about plans to merge the PR you mentioned?

**Comment by krjordan** [comment]
Looks like [July 1](https://github.com/ngrx/platform/issues/25#issuecomment-309138241) is the target date for a new release, so hopefully before then.

**Comment by sharikovvladislav** [comment]
Okay, ty! I am waiting for this date!

**Comment by sharikovvladislav** [comment]
Any news?

**Comment by sharikovvladislav** [comment]
Merged!

**Comment by brandonroberts** [comment]
This has been fixed in the V4 example. If you see any issues, please open them there

**Comment by sharikovvladislav** [comment]
Do you mean there? https://github.com/ngrx/platform

**Comment by sharikovvladislav** [comment]
This issue was not fixed there.
