### ISSUE TITLE
example-app not starting

### ISSUE THREAD

**Issue by JavierDonoso** [ngrx/example-app#59]
hello everybody, new on (programming, git, angular2, ngrx...) but very passionate.

When I tried to install the example app, I follow the instructions; npm install works fine, but npm start throw following message:
Node version:  v6.5.0
NPM version  v3.10.3

Thanks in advance

[npm-debug.zip](https://github.com/ngrx/example-app/files/517550/npm-debug.zip)

**Comment by tja4472** [comment]
Edit package.json so that:
```
    "@ngtools/webpack": "1.0.0",
```
Have just deleted node_modules.
After npm install get:
```
C:\VSCode\ngrx\git-hub\example-app>npm start

> @ngrx/example-app@1.0.0 start C:\VSCode\ngrx\git-hub\example-app
> webpack-dev-server


C:\VSCode\ngrx\git-hub\example-app\webpack.config.js:61
      new NgcWebpackPlugin({
      ^
TypeError: NgcWebpackPlugin is not a constructor
    at module.exports (C:\VSCode\ngrx\git-hub\example-app\webpack.config.js:61:7)
    at requireConfig (C:\VSCode\ngrx\git-hub\example-app\node_modules\webpack\bin\convert-argv.js:117:15)
    at C:\VSCode\ngrx\git-hub\example-app\node_modules\webpack\bin\convert-argv.js:124:17
    at Array.forEach (native)
    at module.exports (C:\VSCode\ngrx\git-hub\example-app\node_modules\webpack\bin\convert-argv.js:122:15)
    at Object.<anonymous> (C:\VSCode\ngrx\git-hub\example-app\node_modules\webpack-dev-server\bin\webpack-dev-server.js:142:48)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tim\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
```
Previous working:
```
+-- @angular/common@2.0.1
+-- @angular/compiler@2.0.1
+-- @angular/compiler-cli@0.6.3
+-- @angular/core@2.0.1
+-- @angular/forms@2.0.1
+-- @angular/http@2.0.1
+-- @angular/material@2.0.0-alpha.9-3
+-- @angular/platform-browser@2.0.1
+-- @angular/platform-browser-dynamic@2.0.1
+-- @angular/platform-server@2.0.1
+-- @angular/router@3.0.1
+-- @ngrx/core@1.2.0
+-- @ngrx/db@2.0.1
+-- @ngrx/effects@2.0.0
+-- @ngrx/router-store@1.2.4
+-- @ngrx/store@2.2.1
+-- @ngrx/store-devtools@3.1.0
+-- @ngtools/webpack@1.0.0
+-- @types/hammerjs@2.0.33
+-- awesome-typescript-loader@2.2.4
+-- codelyzer@0.0.19
+-- core-js@2.4.1
+-- cpy-cli@1.0.1
+-- css-loader@0.25.0
+-- es6-promise@3.3.1 extraneous
+-- es6-promise-loader@1.0.2 extraneous
+-- es6-shim@0.35.1 extraneous
+-- html-loader@0.4.4
+-- html-webpack-plugin@2.22.0
+-- json-loader@0.5.4
+-- ngrx-store-freeze@0.1.0
+-- raw-loader@0.5.1
+-- rimraf@2.5.4
+-- rxjs@5.0.0-beta.12
+-- source-map-loader@0.1.5
+-- string-replace-loader@1.0.5
+-- style-loader@0.13.1
+-- ts-helpers@1.1.1
+-- ts-node@0.7.3
+-- tslint@3.15.1
+-- tslint-loader@2.1.5
+-- typescript@2.0.2
+-- webpack@2.1.0-beta.25
+-- webpack-dev-server@2.1.0-beta.8
`-- zone.js@0.6.25
```

**Comment by JavierDonoso** [comment]
Thanks very much, now is working.

First Time interacting in git asking for support and that is awesome!!!!!!!
