### ISSUE TITLE
Error having running npm start after clean install

### ISSUE THREAD

**Issue by beckelmw** [ngrx/example-app#61]
Greetings:

I cloned the the repo, then ran `npm install`. I was missing the rxjs peer dependency so I installed that as well.

I then tried to run `npm start` and received this error:

const {ForkCheckerPlugin} = require('awesome-typescript-loader');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at requireConfig (/Users/bbechelman/Projects/example-app/node_modules/webpack/bin/convert-argv.js:111:18)
    at /Users/bbechelman/Projects/example-app/node_modules/webpack/bin/convert-argv.js:124:17
    at Array.forEach (native)

I am running the following:
Node 4.2.4
NPM 3.10.8

**Comment by beckelmw** [comment]
This was pretty straightforward. I just needed an up to date node version that can use es6 syntax. The engines in package.json may need to be updated as it is currently listing 4.2.1.
