### ISSUE TITLE
TypeError: NgcWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by mardo** [ngrx/example-app#62]
Hello!

I did a fresh checkout of this repo, then did an `npm install` and when I tried to start the server with `npm start` I had this output:

> @ngrx/example-app@1.0.0 start /Users/mardo/gitClones/example-app
> webpack-dev-server

/Users/mardo/gitClones/example-app/webpack.config.js:61
      new NgcWebpackPlugin({
      ^
TypeError: NgcWebpackPlugin is not a constructor
    at module.exports (/Users/mardo/gitClones/example-app/webpack.config.js:61:7)
    at requireConfig (/Users/mardo/gitClones/example-app/node_modules/webpack/bin/convert-argv.js:117:15)
    at /Users/mardo/gitClones/example-app/node_modules/webpack/bin/convert-argv.js:124:17
    at Array.forEach (native)
    at module.exports (/Users/mardo/gitClones/example-app/node_modules/webpack/bin/convert-argv.js:122:15)
    at Object.<anonymous> (/Users/mardo/gitClones/example-app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:148:48)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/mardo/.nvm/versions/node/v6.8.0/bin/node" "/Users/mardo/.nvm/versions/node/v6.8.0/bin/npm" "start"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ngrx/example-app@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ngrx/example-app@1.0.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @ngrx/example-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @ngrx/example-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @ngrx/example-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mardo/gitClones/example-app/npm-debug.log

Any ideas why is this happening?

**Comment by mardo** [comment]
Fixed by doing:

```
rm -rf ./node_modules
npm cache clean
npm install
```

**Comment by melmanot** [comment]
@mardo this solution is not working in windows.

rmdir /s .\node_modules
npm cache clean 
npm install
