### ISSUE TITLE
Can't make AOT build

### ISSUE THREAD

**Issue by llekn** [ngrx/example-app#96]
Trying to build the example-app from `fb3cf1` with AoT throws an error with the following stack trace:
```
TypeError: ngCompiler.ReflectorHost is not a constructor
    at AotPlugin._setupOptions (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/@ngtools/webpack/src/plugin.js:127:31)
    at new AotPlugin (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/@ngtools/webpack/src/plugin.js:35:14)
    at Object.exports.getWebpackAotConfigPartial (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/angular-cli/models/webpack-build-typescript.js:57:13)
    at new NgCliWebpackConfig (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/angular-cli/models/webpack-config.js:18:42)
    at Class.run (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/angular-cli/tasks/build-webpack.js:17:22)
    at Class.run (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/home/camilo/workspace/llekn/angular2/ngrx-example-app/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Steps to reproduce the problem:
1. Clone the repo: `git clone https://github.com/ngrx/example-app.git`
2. Install dependencies using yarn: `yarn`
3. Try to make an AoT build: `ng build --aot`

It would be nice to have this example AoT compatilble since there are some changes to be made to an ngrx/store app to be built this way.

**Comment by kyranjamie** [comment]
Node version?

**Comment by llekn** [comment]
```shell
$ node --version
v6.9.2
```

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/example-app/issues/104
